target("xf_log")
    set_kind("binary")
    add_cflags("-Wall")
    add_cflags("-std=gnu99 -O0 -g")
    add_files("src/*.c")
    add_files("example/*.c")
    add_includedirs("src")
    add_includedirs("src/utils")
    add_includedirs("example")
